// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslIleRqaWV9yHxL4NnXjp8VNdxtLZfq4',
    appId: '1:1058256587860:web:766c742b2e3693941571c1',
    messagingSenderId: '1058256587860',
    projectId: 'masjadna',
    authDomain: 'masjadna.firebaseapp.com',
    storageBucket: 'masjadna.appspot.com',
    measurementId: 'G-JNLBNFX6JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxalIiEvTNmFW8kDHkR7mzsFLd3fA1jvQ',
    appId: '1:1058256587860:android:6f1d65da6353ab201571c1',
    messagingSenderId: '1058256587860',
    projectId: 'masjadna',
    storageBucket: 'masjadna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Jy_hBPlYO7l3sdJdZGKfDZchoGUP1tk',
    appId: '1:1058256587860:ios:395d0fc8bdc751d61571c1',
    messagingSenderId: '1058256587860',
    projectId: 'masjadna',
    storageBucket: 'masjadna.appspot.com',
    iosClientId: '1058256587860-21uqlmm68pl84s7r68ifu4s6tu7bpfpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.masajdna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Jy_hBPlYO7l3sdJdZGKfDZchoGUP1tk',
    appId: '1:1058256587860:ios:395d0fc8bdc751d61571c1',
    messagingSenderId: '1058256587860',
    projectId: 'masjadna',
    storageBucket: 'masjadna.appspot.com',
    iosClientId: '1058256587860-21uqlmm68pl84s7r68ifu4s6tu7bpfpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.masajdna',
  );
}
